version: '3'
services:
  redis1:
    image: redis:7.0.5
    ports:
      - "7000:7000"
      - "17000:17000"
    expose:
      - 7000
      - 17000
    volumes:
      - ./docker-data/redis-cluster1.tmpl:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      app_net:
        ipv4_address: 173.17.0.2
  redis2:
    image: redis:7.0.5
    ports:
      - "7001:7001"
      - "17001:17001"
    expose:
      - 7001
      - 17001
    volumes:
      - ./docker-data/redis-cluster2.tmpl:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      app_net:
        ipv4_address: 173.17.0.3
  redis3:
    image: redis:7.0.5
    ports:
      - "7002:7002"
      - "17002:17002"
    expose:
      - 7002
      - 17002
    volumes:
      - ./docker-data/redis-cluster3.tmpl:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      app_net:
        ipv4_address: 173.17.0.4
  redis-cluster-init:
    tty: true
    image: redis:7.0.5
    volumes:
      - ./docker-data/cluster-script.sh:/usr/local/etc/redis/cluster-script.sh
    hostname: server
    command: sh /usr/local/etc/redis/cluster-script.sh
    depends_on:
      - redis1
      - redis2
      - redis3
    networks:
      app_net:
        ipv4_address: 173.17.0.6
networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 173.17.0.0/16
